### ISSUE TITLE
Helm chart deployment failed (Windows 10)

### ISSUE THREAD

**Issue by hazsetata** [pulumi/pulumi-kubernetes#143]
I try to run the following Helm install, targeting an Azure AKS cluster, on Windows 10 (Pulumi v0.15.0):

```
export const certManagerChart = new helm.v2.Chart("cert-manager", {
    repo: "stable",
    chart: "cert-manager",
    version: "v0.4.1",
}, { providers: { kubernetes: k8sProvider } });
```
And I get an error, something that looks like wrong escaping of drive letter on Windows:

```
Diagnostics:
  pulumi:pulumi:Stack: beyondzen-dev
    info: Error: Failed to untar (mkdir): mkdir C\:: The filename, directory name, or volume label syntax is incorrect.
    error: [runtime] Running program 'C:\<PROJECT_DIR>' failed with an unhandled exception:
    error: [runtime] { Error: Command failed: helm fetch stable/cert-manager --untar --version v0.4.1 --destination C\:\\Users\\<MY_USER>\\AppData\\Local\\Temp\\tmp-141681145pIvQKKyH
    Error: Failed to untar (mkdir): mkdir C\:: The filename, directory name, or volume label syntax is incorrect.
        at checkExecSyncError (child_process.js:601:13)
        at Object.execSync (child_process.js:641:13)
        at fetch (C:\<PROJECT_DIR>\node_modules\@pulumi\kubernetes\helm.js:122:21)
        at new Chart (C:\<PROJECT_DIR>\node_modules\@pulumi\kubernetes\helm.js:31:17)
        at Object.<anonymous> (C:\<PROJECT_DIR>\charts.ts:5:28)
        at Module._compile (module.js:652:30)
        at Module.m._compile (C:\<PROJECT_DIR>\node_modules\ts-node\src\index.ts:439:23)
        at Module._extensions..js (module.js:663:10)
        at Object.require.extensions.(anonymous function) [as .ts] (C:\<PROJECT_DIR>\node_modules\ts-node\src\index.ts:442:12)
        at Module.load (module.js:565:32)
```

**Comment by hausdorff** [comment]
This is a bug in our dependency on the nodejs `shell-quote` package. Should be fixed in #149, and included in v0.15.2.

**Comment by ellismg** [comment]
This is still an issue with 0.16.0.  Alex and I were chatting a bit about it during the hackathon and got something working, but I think we need to do a quick pass over the way we are quoting and shelling everything to make sure stuff is correct and there aren't any other lingering issues.
