### ISSUE TITLE
Helm Chart Trigging a Diff on Each Run for Checksum Changes

### ISSUE THREAD

**Issue by zbuchheit** [pulumi/pulumi-kubernetes#2649]
### What happened?

When attempting to use helm.v3.release, each run is reporting a diff on the checksum property which is unexpected.

### Example

```
const alb = new k8s.helm.v3.Release("alb", {
    chart: "aws-load-balancer-controller",
    namespace: 'default',
    version: "1.6.2",
    skipAwait: false,
    repositoryOpts: {
        repo: "https://aws.github.io/eks-charts",
    },
    values: {
        clusterName: cluster.eksCluster.name
    }
}, { 
    dependsOn: [cluster],
    provider: k8sProvider
});
```
each additional pulumi up after resource creation will result in

```
     Type                              Name                  Plan       Info
     pulumi:pulumi:Stack               aws-ts-eks-zbuchheit             
 ~   └─ kubernetes:helm.sh/v3:Release  alb                   update     [diff: ~checksum]
```

### Output of `pulumi about`

```
CLI          
Version      3.90.1
Go Version   go1.21.3
Go Compiler  gc

Plugins
NAME        VERSION
aws         6.0.3
aws         5.42.0
aws         5.31.0
awsx        1.0.5
docker      3.6.1
eks         1.0.3
kubernetes  4.3.0
kubernetes  3.30.2
nodejs      unknown

Host     
OS       darwin
Version  14.0
Arch     arm64
```

### Additional context

Ignore changes allows for a workaround of this issue, but obviously a diff on the checksum on each subsequent up is not a desired result, especially when attempting to use `--expect-no-changes` in a ci/cd environment. 

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by mikhailshilkov** [comment]
@EronWright Could you please take a look?

**Comment by rhuanbarreto** [comment]
the latest version fixed this. Please try.

**Comment by mikhailshilkov** [comment]
@zbuchheit Indeed, this should have been fixed already, can you give the latest version a try?

**Comment by zbuchheit** [comment]
I am still experiencing this behavior consistently with the provided code snippet.

Oddly enough, I was exporting the resourceNames and I am seeing it attempting to add a resource every time as well. I doesn't show up in the diff but shows up in the output on each run. For example, you can see it attempting to add `CustomResourceDefinition.apiextensions.k8s.io/apiextensions.k8s.io/v1` I am not sure if that is helpful or more confusing, but I am wondering if the diff of resourceNames changing is bubbling up as a checksum diff. 

```shell
     Type                              Name                  Plan       Info
     pulumi:pulumi:Stack               aws-ts-eks-zbuchheit             
 ~   └─ kubernetes:helm.sh/v3:Release  alb                   update     [diff: ~checksum]

Outputs:
  ~ albDetails: {
        ClusterRole.rbac.authorization.k8s.io/rbac.authorization.k8s.io/v1                         : [
            [0]: "alb-f25f1677-aws-load-balancer-controller-role"
        ]
        ClusterRoleBinding.rbac.authorization.k8s.io/rbac.authorization.k8s.io/v1                  : [
            [0]: "alb-f25f1677-aws-load-balancer-controller-rolebinding"
        ]
      + CustomResourceDefinition.apiextensions.k8s.io/apiextensions.k8s.io/v1                      : [
      +     [0]: "ingressclassparams.elbv2.k8s.aws"
      +     [1]: "targetgroupbindings.elbv2.k8s.aws"
        ]
        Deployment.apps/apps/v1                                                                    : [
            [0]: "default/alb-f25f1677-aws-load-balancer-controller"
        ]
        List/v1                                                                                    : [
            [0]: "ingress-class"
        ]
        MutatingWebhookConfiguration.admissionregistration.k8s.io/admissionregistration.k8s.io/v1  : [
            [0]: "aws-load-balancer-webhook"
        ]
        Role.rbac.authorization.k8s.io/rbac.authorization.k8s.io/v1                                : [
            [0]: "default/alb-f25f1677-aws-load-balancer-controller-leader-election-role"
        ]
        RoleBinding.rbac.authorization.k8s.io/rbac.authorization.k8s.io/v1                         : [
            [0]: "default/alb-f25f1677-aws-load-balancer-controller-leader-election-rolebinding"
        ]
        Secret/v1                                                                                  : [
            [0]: "default/aws-load-balancer-tls"
        ]
        Service/v1                                                                                 : [
            [0]: "default/aws-load-balancer-webhook-service"
        ]
        ServiceAccount/v1                                                                          : [
            [0]: "default/alb-f25f1677-aws-load-balancer-controller"
        ]
        ValidatingWebhookConfiguration.admissionregistration.k8s.io/admissionregistration.k8s.io/v1: [
            [0]: "aws-load-balancer-webhook"
        ]
    }

Resources:
    ~ 1 to update
    51 unchanged```

**Comment by mausch** [comment]
I'm still seeing this on v4.5.3

**Comment by rhuanbarreto** [comment]
Tried on v4.5.4. Finally the kube version problem was solved. But this checksum is still problematic.

Differently from previous versions, ignoring the changes on it (like @mausch reported) actually works.

**Comment by mitchellmaler** [comment]
Just upgraded to provider v4.5.4 on Python, and we are seeing the same. Each Release resource shows the checksum changed when none of the inputs were changed.

**Comment by biasedbit** [comment]
Adding to the pile, I'm observing this with `aws-load-balancer-controller` and `datadog-agent` charts — the latter is rather problematic as it takes a long time to restart every datadog-agent pod in the cluster (which would make deployments much longer than necessary).

Adding `ignore_changes=["checksum"]` prevents the undesirable side-effect.

```
pulumi-docker==4.4.5
pulumi-eks==2.0.0
pulumi==3.93.0
```

**Comment by EronWright** [comment]
Thanks everyone for the bug details. The root cause of the issue is that some charts have randomly generated content, such as passwords and/or tokens.  For example, the `datadog-agent` chart generates a value for `clusterAgent.token` when one isn't supplied by the user.  A subsequent upgrade would generate a fresh token in this case, and Pulumi detects that.

The original purpose of the checksum is to determine whether a local chart has changed, necessitating an upgrade. The practical solution is to not based the checksum on the output from `helm template`, but to simply base it on the literal local chart contents. Thoughts?

**Comment by rhuanbarreto** [comment]
@EronWright then it would be good to have a way to explicitly identify which field is being modified underneath so we could set a static value on it. Today it looks like a guessing work once only the checksum is changed.

**Comment by EronWright** [comment]
@rhuanbarreto my proposal is that the checksum not be calculated, since it is volatile, and that Chart version be the determinant.

**Comment by rhuanbarreto** [comment]
@EronWright I agree. What I normally use as a reference is the version.

**Comment by mitchellmaler** [comment]
@EronWright I have upgraded pulumi-kubernetes to 4.5.5 using python and I am still seeing the checksum show in helm release diffs. Was this supposed to be resolved in that version? If so I can log a new issue.
