### ISSUE TITLE
Helm Error: invalid chart URL format

### ISSUE THREAD

**Issue by ameier38** [pulumi/pulumi-kubernetes#623]
__Issue 1__
I am trying to install the following chart:
```ts
export const openfaas = new k8s.helm.v2.Chart(
    'openfaas',
    {
        chart: 'openfaas',
        repo: 'https://openfaas.github.io/faas-netes',
        version: '4.3.5',
        namespace: openfaasNamespace.metadata.name,
        values: {
            functionNamespace: openfaasFunctionNamespace.metadata.name,
            serviceType: 'ClusterIP',
            basic_auth: true,
            rbac: true,
            faasnetes: {
                httpProbe: false
            }
        }
    },
    {
        provider: devK8sProvider,
        dependsOn: openfaasBasicAuth
    }
)
```
But I keep getting an error `Error: invalid chart URL format: https\://openfaas.github.io/faas-netes/openfaas`
> Note the backslash before the colon.

I see #539 already identified this but it still does not seem to be working.

__Issue 2__
Even if the url was corrected, the command still returns a `404` for this repo.
```
helm fetch https://openfaas.github.io/faas-netes/openfaas
Error: Failed to fetch https://openfaas.github.io/faas-netes/openfaas : 404 Not Found
```

If I change to use the `--repo` flag then the command works.
```
 helm fetch --repo https://openfaas.github.io/faas-netes openfaas
```

__Pulumi Version__:
```
 pulumi version
v0.17.21
```

__Helm Version__:
```
helm version
Client: &version.Version{SemVer:"v2.14.1", GitCommit:"5270352a09c7e8b6e8c9593002a73535276507c0", GitTreeState:"clean"}
```

__Operating System__: Windows 10 Pro Version 10.0.18362 Build 18362

**Comment by hausdorff** [comment]
What version of the `@pulumi/kubernetes` dependency is in your `package.json`? This should have been solved.

**Comment by ameier38** [comment]
Just updated and still the same error.
`pulumi version`:
```
v0.17.22
```
`pulumi up`:
```
Diagnostics:
  pulumi:pulumi:Stack (easury-dev):
    Error: invalid chart URL format: https\://openfaas.github.io/faas-netes/openfaas

    error: Error: Command failed: helm fetch https\://openfaas.github.io/faas-netes/openfaas --untar --version 4.4.0 --destination C:\Users\andy\AppData\Local\Temp\tmp-43012Bwhwey0DtODl
    Error: invalid chart URL format: https\://openfaas.github.io/faas-netes/openfaas
```
In `package-lock.json`:
```json
        "@pulumi/kubernetes": {
            "version": "0.25.2",
            "resolved": "https://registry.npmjs.org/@pulumi/kubernetes/-/kubernetes-0.25.2.tgz",
            "integrity": "sha512-f/hRxbN+HCjY1ZU8jOBpB5wajhs2+nYTH7tc19edphpRBDcZP7RI4VFjOGNyDz+HM51M1AErf5yfsr85qzVbBw==",
            "requires": {
                "@pulumi/pulumi": "^0.17.18",
                "@types/glob": "^5.0.35",
                "@types/js-yaml": "^3.11.2",
                "@types/node-fetch": "^2.1.4",
                "@types/tmp": "^0.0.33",
                "glob": "^7.1.2",
                "js-yaml": "^3.12.0",
                "node-fetch": "^2.3.0",
                "shell-quote": "^1.6.1",
                "tmp": "^0.0.33"
            }
        },
```

**Comment by ameier38** [comment]
The work around for me was to use `fetchOpts`:
```ts
export const openfaasChart = new k8s.helm.v2.Chart(
    'openfaas',
    {
        chart: 'openfaas',
        version: '4.4.0',
        fetchOpts: {
            repo: 'https://openfaas.github.io/faas-netes/'
        },
        namespace: openfaasNamespace.metadata.name
    }
)
```

**Comment by lukehoban** [comment]
We could improve the error message here to identify when a URL is passed instead of a repo name and note that `fetchOps` should be used instead.
